export const rootUrl = 'http://localhost:6600/api/'

export const login = rootUrl + 'login'
export const signup = rootUrl + 'signup'
export const getUserDetails = rootUrl + 'userdetails'
export const getAllProductDetails = rootUrl + 'getAllProductDetails'
export const addProduct = rootUrl + 'addProduct'
export const updateProductDetails = rootUrl + 'updateProductDetails'
export const addTransaction = rootUrl + 'addTransaction'
export const updateQuantity = rootUrl + 'updateQuantity'
export const deleteTransaction = rootUrl + 'deleteTransaction'
export const getTransactionsForUser = rootUrl + 'getTransactionsForUser'
export const getOrderDetailByID = rootUrl + 'getOrderDetailByID'
export const placeOrder = rootUrl + 'placeOrder'